### ISSUE TITLE
write/read auth token to/from dot file

### ISSUE THREAD

**Issue by noahdietz** [30x/shipyardctl#28]
Have `shipyardctl get token` write the generated token to a `~/.shipyardctl/token` file. Have subsequent API calls with `shipyardctl` read from this file (rather than from env/flag). Prompt them to refresh if it has expired.

**Comment by whitlockjc** [comment]
We might reconsider calling this `shipyardctl login` as that's what Docker and similar uses.  There are also discussions about having a `login` command for `kubectl` as well.

**Comment by whitlockjc** [comment]
Closing this in favor of the more general #40.
