### ISSUE TITLE
Add org + env to config file

### ISSUE THREAD

**Issue by noahdietz** [30x/shipyardctl#32]
Figure out how to include the Apigee `org` and `env` values in the config file.

**Comment by whitlockjc** [comment]
I'm not sure this makes as much sense, but it could.  I'd love to hear your thoughts on this.

**Comment by noahdietz** [comment]
I wanted to give this more thought, as Will thought it would be really helpful.

I agree it would be awesome, but they are too transient of values, it is too easy to have multiple org/env combos at your disposal, managing them would get hairy.

Every other Apigee CLI has the user provide org/env, anyways.

Closing.
