### ISSUE TITLE
Shipyard UX Refactor

### ISSUE THREAD

**Issue by AdamMagaluk** [30x/shipyardctl#43]
Proposed updates to the cli from the "Proposed updated steps for Shipyard" doc. 

1. Login From `shipyardctl login` to `shipyardctl logon` _What was the motivation behind this?_

1. Remove environment commands.

1. Create application revision. `shipyardctl import application --name "echo-app1" [--revision 1] --path "9000:/echo-app" -d . -o acme --node-version 4 --env {name1}={value1} --env {name2}={value2}`

1. Get application revision. `shipyardctl get application -o acme --name "echo-app1" [--revision 1] `
1. Deploy an application revision. `shipyardctl create deployment -o acme -e test --name "echo-app-deployment" --app "echo-app" [--revision 1] `

1. Create and upload a proxy bundle to Edge. `shipyardctl deploy proxy -o acme -e test -n "my-app-proxy"`

1. Create a proxy bundle locally. `shipyardctl create bundle -n "my-app-proxy" . `

**Comment by jbowen93** [comment]
This may be beyond the scope of this issue but if/when should we consider a web based UI/UX?

**Comment by AdamMagaluk** [comment]
Closing covered in #52
