### ISSUE TITLE
Remove ability to create an environment

### ISSUE THREAD

**Issue by whitlockjc** [30x/shipyardctl#48]
When https://github.com/30x/enrober/issues/86 is completed, we need to remove `shipyarctl create environment` and rely on `enrober` creating environments on an as-needed basis.

**Comment by noahdietz** [comment]
Should we get rid of the `shipyardctl get | delete | patch environment` commands as well?

**Comment by whitlockjc** [comment]
I think we should keep them for now.  The idea is we want all environments to be created automatically, although we've not really decided on which Shipyard events would create them beyond creating a deployment.  That being said, you'll still need a way to get the details, update and delete an environment after it's been created.

Maybe @mpnally can comment here or in https://github.com/30x/enrober/issues/86 to suggest which Shipyard APIs should create an environment automatically.

**Comment by noahdietz** [comment]
In that case, `get` and `patch` cmds are fine to stay, but I'd be a bit hesitant about keeping the `delete` cmd, in case a user uses it out of curiosity, but can't create another without again going through whatever process we create to automate creating environments...a question of how much rope we want to give users to hang themselves with 😄  maybe we can have the inverse of whatever process creates environments, also delete them?

**Comment by jbowen93** [comment]
I'll hopefully have at least a first pass of #86 done today.

**Comment by noahdietz** [comment]
I'm fine to keep `delete` if it is going to be useful, just thought I'd throw a wrench into things 😛

**Comment by jbowen93** [comment]
The idea of potentially editing/deleting environments that you can't create manually likely justifies a little bit more discussion.

**Comment by mpnally** [comment]
I agree it makes sense to keep `shipyardctl get environment -o acme -e test`. This command gives you the "container info" for your Edge environment. I do not think it makes sense to have delete, since the only thing that exists in the user model is the Edge environment and so the only thing you can delete is the edge environment. `shipyardctl patch environment -o acme -e test` could make sense for patching the "container info" for an edge environment. What information can you patch? I believe that some of the information we used to patch is now disappearing into KVM maps. Is there anything left? If not, se should remove `shipyardctl patch`

Maybe `shipyardctl get container-info -o acme -e test` would make more sense than `shipyardctl get environment -o acme -e test`. Or even `shipyardctl get hosted-target-info -o acme -e test`. Similar for patch (assuming there is anything patchable). 

Other than deploy, I'm not sure if other actions need to trigger creation of K8S resources.

**Comment by whitlockjc** [comment]
I agree that `delete` is an edge case that might not make sense to support.  Maybe we keep `create`/`delete` APIs but do not expose them?  I can see these being useful for cleanup/debugging.  Thoughts?

And as I was about to submit this, the more I think that since we're currently mapping Shipyard environments to namespaces, we could remove these APIs and just use core Kubernetes commands for cleanup/debugging.

**Comment by noahdietz** [comment]
I agree w/ @whitlockjc in the above that using k8s commands/kubectl should be good enough to debug/cleanup....after all, `kubectl delete namespace` does a cascading delete of all resources inside of it, makes for quick cleanup

**Comment by mpnally** [comment]
Yes, for debugging we can just use K8S commands. `shipyardctl get hosted-target-info -o acme -e test` would give me info across multiple regions, so is not just a simple K8S command. It might also give me info on not-yet-deployed hosted-targets, and also previosuly-existed-but-now-deleted hosted-targets. K8S would not know about those.

**Comment by jbowen93** [comment]
Worth noting that the only thing a `patch` on an environment could edit is the list of `hostNames` that are stored on the environment. Also worth questioning whether we want this information to still be stored as annotations or if we should be storing this information as a secret/configMap.

**Comment by mpnally** [comment]
hostNames should come from Edge. Edge already knows this information—we just need to retrieve it. If this is all we patch, then patch can be removed.

**Comment by mpnally** [comment]
I think the primary user of the hostNames annotation is @whitlockjc when he generates the nginx config. I don't know what the consequences would be for him of moving the data to a configMap. All the applications we have written so far get the hostName from the host header in the incoming request, so they don't need to get it from an environment variable and don't need a configMap. However, having an option to get it from an environment variable would be useful for people who can't or won't get the info from a host header. An example would be a daemon (in the unix sense, not the K8S sense) that initiates requests that are not part of the processing of an incoming request. For those people, having the hostNames in a configMap might be useful.

**Comment by jbowen93** [comment]
It's worth pointing out that in the current state there is no validation to confirm that a user "owns" the hostName they are assigning to an environment. We simply have a first come first serve system right now. If we can solve the larger issue of `k8s controller` -> `edge` communication then it may be better to list hostNames as a subset of virtual hosts at the edge level.

**Comment by whitlockjc** [comment]
I think if we do this based on the Apigee Edge environment, it would make it impossible for someone to steal someone's host.  But of course, this just makes the issue discussed in https://github.com/30x/project-management/issues/189 much more important to solve.

**Comment by jbowen93** [comment]
Agreed. We need to make a time to discuss that issue thoroughly.

**Comment by mpnally** [comment]
I agree that 30x/project-management#189 is important, but we don't need a full resolution of that in order to get hostNames from Edge. All we need to do is read the values from Edge when the K8S namespace is created and define some approach to refresh. We could refresh on each deploy, for example, or on a time period, like Edge microgateway does.

**Comment by whitlockjc** [comment]
Well, we do need to solve this.  Because either we build a system with features that allow you to work around this, like a manual endpoint or something, that needs to be designed/implemented or we build things right the first time.  But yes, I bet we could come up with the simpler, more manual approach now if you're fine with that.

**Comment by mpnally** [comment]
I think the right model is the EdgeX/apid model, but we don't have that yet. I think it's OK to do some workarounds now, and converge on apid in the second half of 2017. If we try to do anything fancy, there is a danger we end up competing with apid.

**Comment by whitlockjc** [comment]
That's what https://github.com/30x/project-management/issues/189 is intending to do, get us to agree upon an MVP or sorts so we can design things like the router, application configuration, etc.  So while that issue will not design/solve the greater issue, it will get us all on the same page with where we can go now.

**Comment by mpnally** [comment]
Makes sense. Lets dedicate tomorrow's parking-lot discussion to this

**Comment by whitlockjc** [comment]
Works for me.  I'll start thinking about what this looks like.

**Comment by noahdietz** [comment]
I am going to open a PR to start this. I will remove all environment commands one-be-one in different commits in case we change our mind on some of them for whatever reason...

**Comment by whitlockjc** [comment]
I think removing all environment commands is not ideal.  Since we will be storing some data in the environment itself, like routing hosts, it would be useful to get/update an environment.  Thoughts?

**Comment by jbowen93** [comment]
@whitlockjc Currently we are leaving both the `GET` and `PATCH` functionality on an environment.

**Comment by whitlockjc** [comment]
Great.

**Comment by noahdietz** [comment]
I'm going to close this PR. Going to just make the changes in the refactor PR.
