### ISSUE TITLE
patch deployment cmd

### ISSUE THREAD

**Issue by noahdietz** [30x/shipyardctl#54]
So as discussed in #49 , the `patch` command will be removed with the other `environment` based commands. There is also a version of the subcommand for `deployment`. 

There will be a new `deploy application` cmd per #51 , replacing `create deployment`. Do we keep a `patch deployment`? Or expose the various mutable properties of a deployment as individual cmd?

For example (just example, not saying these are the ones) `shipyardctl deploy revision -o acme -e test -n example:4` to update a deployment image version or `shipyardctl deploy config -o acme -e test -n example --env-var="NEW=VAR" --kvm-var="TEST=VAL"` to add env/kvm variables to a deployment's spec.

thoughts @whitlockjc @jbowen93 @mpnally @AdamMagaluk ?

**Comment by whitlockjc** [comment]
I think `patch deployment` should probably be called `update deployment`.

/cc @mpnally
